services:
  postgres:
    image: postgres:16
    container_name: debtmate-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: debtmate
      POSTGRES_DB: debtmate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - debtmate-network

volumes:
  postgres_data:

networks:
  debtmate-network:
    driver: bridge
